name: Build APK

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true

      - name: Spotless Check
        run: ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Build
        run: ./gradlew assembleDefaultRelease

      - name: List files
        run: ls app/build/outputs/apk/default/release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: cg-${{ github.sha }}
          path: app/build/outputs/apk/default/release/app-default-release.apk