name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Rename APK to include tag
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-${{ github.ref }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: New version
          files: app/build/outputs/apk/release/app-${{ github.ref }}.apk