name: Create Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Gradle Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleRelease

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release-unsigned.apk cg-${{ github.ref_name }}.apk

      - name: Release APK
        uses: softprops/action-gh-release@v2
        with:
          body: New version
          files: cg-${{ github.ref_name }}.apk